name: Nasa Project CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    setps:
      - uses: actions/checkout@v3
      - name: Use NodeJS with version 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - run: npm run build --prefix client